### ISSUE TITLE
Would it be possible for you to implement a way to download from gelbooru with this program?

### ISSUE THREAD

**Issue by KylarZeppeli** [FerrahWolfeh/imageboard-downloader-rs#1] opened 2022-08-21 14:23 UTC
Also, is it possible to implement a "post limit", where the program quits downloading after "X" amount of posts have been downloaded?

**Comment by FerrahWolfeh** [comment] 2022-08-21 14:33
Sure, both are possible to implement. Although the program is more of a "per-site" downloader, it's not a bad idea at all to implement a generic api downloader for gelbooru, since the API between these websites doesn't differ very much.

**Comment by KylarZeppeli** [comment] 2022-08-21 15:02
Would you be willing to implement them? I'm not a coder by any means so I can't do it myself, sadly.

**Comment by FerrahWolfeh** [comment] 2022-08-21 15:49
I worked on it a little. 
The download limiter is probably going to take a while because currently it's more of a hack
The gelbooru download option is almost ready, btw

**Comment by KylarZeppeli** [comment] 2022-08-21 16:07
Nice! This is the best rule34 downloader I've found here & my old gelbooru downloader broke & hasn't been updated since 2020 so I had to find a new one

**Comment by FerrahWolfeh** [comment] 2022-08-21 18:54
I finished implementing both, but I need some thorough testing as the code's still a little messy.

Please rebuild it from the latest `main` and check if any issues appear

**Comment by KylarZeppeli** [comment] 2022-08-21 23:41
The new gelbooru downloader you implemented *appears* to be working perfectly, but I did find some issues with the download limiter, anything over 100 for Gelbooru or 1000 for Rule34 makes the program crash without downloading anything

Error message for Rule34 downloader with 1001+ as the download limit:
thread 'main' panicked at 'range end index 1002 out of range for slice of length 1000', library/core/src/slice/index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error message for Gelbooru downloader with 101+ as the download limit:
thread 'main' panicked at 'range end index 102 out of range for slice of length 100', library/core/src/slice/index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I'm assuming you can just change the "range for slice of length" to 100,000 or something?

**Comment by FerrahWolfeh** [comment] 2022-08-21 23:47
Okay, I kinda know what the issue is. Sort of an oversight from my part

What happens is because of the API limit of those websites. when the limiter tries to "remove" 1001 posts from the batch, its trying to remove more than it has in it.

Luckily to fix this I just need to do some (more) math

**Comment by KylarZeppeli** [comment] 2022-08-21 23:48
Also, this is minor but I think that the download directory names would look nicer if it was formatted like "tag1 tag2" instead of "tag1+tag2" A space instead of the plus sign

**Comment by FerrahWolfeh** [comment] 2022-08-22 02:02
I managed to fix that and tackled another annoying bug in the proccess.

try to rebuild from latest `main` and see if the limiter is now working as intended

**Comment by KylarZeppeli** [comment] 2022-08-22 03:35
What I was referring to in my previous comment was not fixed in the latest commit but I think I found the line that was generating the plus signs in the directory names
Line 11 on "src/imageboards/macros.rs" - let tl = $x.join("+");
Changing the plus sign on that line changes what's between the tags but I don't know how to make it just be an empty space
Other than that, everything works perfectly & I haven't found any more bugs & I have no more suggestions for you
:) thanks!

**Comment by FerrahWolfeh** [comment] 2022-08-22 13:18
That line was for creating the url parameters for the tags themselves, happens that I was just reusing the result to create the output dir.

**Comment by FerrahWolfeh** [comment] 2022-08-22 13:18
Since now all things were dealt with, i'm closing the issue. Cheers!

**Closed as completed by FerrahWolfeh** 2022-08-22 13:18 UTC
